name: aws-athena-workgroup-plugin
description: Plugin para faciliar a criação de WorkGroup no Athena para começar com as consultas em ambiente Big Data
display-name: aws-athena-workgroup-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - env
inputs:
  - label: Nome do WorkGroup
    type: text
    name: workgroup_name

  - label: Limite de gigas para escanear em uma consulta (em Gigabytes)
    type: int
    name: gigas_scanned
    default: "150"

  - label: Nome do bucket de saída dos dados
    type: text
    name: bucket_name

  - label: Example of list
    type: text
    name: encryption_option
    items:
      - SSE_KMS
      - CSE_KMS
      - SSE_S3
    default: "SS3_S3"

  - label: Arn da chave KMS
    type: text
    name: kms_key_arn
    condition:
      variable: encryption_option
      operator: "!="
      value: SSE_S3

global-computed-inputs:
  bytes_scanned: "{{inputs.gigas_scanned * 1073741824}}"
