name: aws-athena-workgroup-plugin
description: Plugin para faciliar a criação de WorkGroup no Athena para começar com as consultas em ambiente Big Data
display-name: aws-athena-workgroup-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - env
inputs:
  - label: Input Example
    type: text
    name: example
    default: any text
  - label: Example of number
    type: int
    name: any_number
    default: "10"
  - label: Example of list
    type: multiselect
    name: any_list
    items:
      - item1
      - item2
